
name: Docker Permissions

on: 
  push
    # branches-ignore:
    #   - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test_docker_perms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show environment
      run: docker version

    - name: Create temp directory
      run: |
        mkdir temp
        ls -la
        echo "hello direct" > ./temp/direct.txt
        ls -la temp
        pwd





    - name: Build Docker image
      run: |
        docker build -t maxjeffostest .
        docker image ls

    - name: Create file in container
      run: |
        docker run --rm -v $(pwd)/temp:/mounted maxjeffostest:latest
        ls -la temp
        mv ./temp/container.txt ./temp/container-no-user-passed.txt
        ls -la temp

    - name: Show user/group stuff
      run: |
        id

    - name: Create file in container with passed user/group
      run: |
        docker run --rm -u 1001:121 -v $(pwd)/temp:/mounted maxjeffostest:latest
        mv ./temp/container.txt ./temp/container-with-user-passed.txt


    - name: Build Docker image that changes user
      working-directory: ./docker-change-user
      run: |
        ls -la
        ./db.sh
        docker image ls

    - name: Create file in container that changes user
      run: |
        export USER_ID=$(id -u)
        docker run --rm -e USER_ID -v $(pwd)/temp:/mounted maxjeffos-change-user:latest
        ls -la temp



    - name: Show temp directory
      run: |
        ls -la temp

    - name: Delete the files
      run: |
        ls -la temp
        rm temp/*
        ls -la temp
        groups
        sudo cat /etc/sudoers
